function u = u_NN1(x,t,rou,theta,k,c,x0)
cc = conj(c);
u = exp(1).^((sqrt(-1)*2).*rou.^2.*t).*rou.*((-1).*c.*cc+c.*exp(1).^(sqrt(-1).*exp(1).^((sqrt(-1)*(-2)) ...
  .*theta).*rou.^2.*t+(sqrt(-1)*(-1)).*exp(1).^((sqrt(-1)*2).*theta).*rou.^2.*t+(-1).*exp(1).^((sqrt( ...
  -1)*(-1)).*theta).*rou.*x+(-1).*exp(1).^(sqrt(-1).*theta).*rou.*x+(-1).*exp(1).^((sqrt(-1)*(-1)).* ...
  theta).*rou.*((-1).*k+(-1).*x0)+(-1).*exp(1).^(sqrt(-1).*theta).*rou.*((-1).*k+(-1).*x0)).*((-1).* ...
  exp(1).^((sqrt(-1)*(-1)).*theta).*rou+(-1).*exp(1).^(sqrt(-1).*theta).*rou).^(-1)+(-1).*exp(1).^( ...
  exp(1).^((sqrt(-1)*(-1)).*theta).*k.*rou+exp(1).^(sqrt(-1).*theta).*k.*rou+(sqrt(-1)*2).*exp(1).^(( ...
  sqrt(-1)*(-2)).*theta).*rou.^2.*t+(sqrt(-1)*(-2)).*exp(1).^((sqrt(-1)*2).*theta).*rou.^2.*t+(-1).* ...
  exp(1).^((sqrt(-1)*(-1)).*theta).*rou.*((-1).*k+(-1).*x0)+(-1).*exp(1).^(sqrt(-1).*theta).*rou.*(( ...
  -1).*k+(-1).*x0)).*(exp(1).^((sqrt(-1)*(-1)).*theta).*rou+(-1).*exp(1).^(sqrt(-1).*theta).*rou).^( ...
  -1).*((-1).*exp(1).^((sqrt(-1)*(-1)).*theta).*rou+exp(1).^(sqrt(-1).*theta).*rou).^(-1)+(-1).*cc.* ...
  exp(1).^(exp(1).^((sqrt(-1)*(-1)).*theta).*k.*rou+exp(1).^(sqrt(-1).*theta).*k.*rou+sqrt(-1).*exp(1) ...
  .^((sqrt(-1)*(-2)).*theta).*rou.^2.*t+(sqrt(-1)*(-1)).*exp(1).^((sqrt(-1)*2).*theta).*rou.^2.*t+exp( ...
  1).^((sqrt(-1)*(-1)).*theta).*rou.*x+exp(1).^(sqrt(-1).*theta).*rou.*x).*(exp(1).^((sqrt(-1)*(-1)).* ...
  theta).*rou+exp(1).^(sqrt(-1).*theta).*rou).^(-1)+exp(1).^(exp(1).^((sqrt(-1)*(-1)).*theta).*k.*rou+ ...
  exp(1).^(sqrt(-1).*theta).*k.*rou+(sqrt(-1)*2).*exp(1).^((sqrt(-1)*(-2)).*theta).*rou.^2.*t+(sqrt( ...
  -1)*(-2)).*exp(1).^((sqrt(-1)*2).*theta).*rou.^2.*t+(-1).*exp(1).^((sqrt(-1)*(-1)).*theta).*rou.*(( ...
  -1).*k+(-1).*x0)+(-1).*exp(1).^(sqrt(-1).*theta).*rou.*((-1).*k+(-1).*x0)).*((-1).*exp(1).^((sqrt( ...
  -1)*(-1)).*theta).*rou+(-1).*exp(1).^(sqrt(-1).*theta).*rou).^(-1).*(exp(1).^((sqrt(-1)*(-1)).* ...
  theta).*rou+exp(1).^(sqrt(-1).*theta).*rou).^(-1)).^(-1).*((-1).*c.*cc+(-1).*c.*exp(1).^(sqrt(-1).* ...
  exp(1).^((sqrt(-1)*(-2)).*theta).*rou.^2.*t+(sqrt(-1)*(-1)).*exp(1).^((sqrt(-1)*2).*theta).*rou.^2.* ...
  t+(sqrt(-1)*2).*theta+(-1).*exp(1).^((sqrt(-1)*(-1)).*theta).*rou.*x+(-1).*exp(1).^(sqrt(-1).*theta) ...
  .*rou.*x+(-1).*exp(1).^((sqrt(-1)*(-1)).*theta).*rou.*((-1).*k+(-1).*x0)+(-1).*exp(1).^(sqrt(-1).* ...
  theta).*rou.*((-1).*k+(-1).*x0)).*((-1).*exp(1).^((sqrt(-1)*(-1)).*theta).*rou+(-1).*exp(1).^(sqrt( ...
  -1).*theta).*rou).^(-1)+(-1).*exp(1).^(exp(1).^((sqrt(-1)*(-1)).*theta).*k.*rou+exp(1).^(sqrt(-1).* ...
  theta).*k.*rou+(sqrt(-1)*2).*exp(1).^((sqrt(-1)*(-2)).*theta).*rou.^2.*t+(sqrt(-1)*(-2)).*exp(1).^(( ...
  sqrt(-1)*2).*theta).*rou.^2.*t+(sqrt(-1)*4).*theta+(-1).*exp(1).^((sqrt(-1)*(-1)).*theta).*rou.*(( ...
  -1).*k+(-1).*x0)+(-1).*exp(1).^(sqrt(-1).*theta).*rou.*((-1).*k+(-1).*x0)).*(exp(1).^((sqrt(-1)*(-1) ...
  ).*theta).*rou+(-1).*exp(1).^(sqrt(-1).*theta).*rou).^(-1).*((-1).*exp(1).^((sqrt(-1)*(-1)).*theta) ...
  .*rou+exp(1).^(sqrt(-1).*theta).*rou).^(-1)+cc.*exp(1).^(exp(1).^((sqrt(-1)*(-1)).*theta).*k.*rou+ ...
  exp(1).^(sqrt(-1).*theta).*k.*rou+sqrt(-1).*exp(1).^((sqrt(-1)*(-2)).*theta).*rou.^2.*t+(sqrt(-1)*( ...
  -1)).*exp(1).^((sqrt(-1)*2).*theta).*rou.^2.*t+(sqrt(-1)*2).*theta+exp(1).^((sqrt(-1)*(-1)).*theta) ...
  .*rou.*x+exp(1).^(sqrt(-1).*theta).*rou.*x).*(exp(1).^((sqrt(-1)*(-1)).*theta).*rou+exp(1).^(sqrt( ...
  -1).*theta).*rou).^(-1)+exp(1).^(exp(1).^((sqrt(-1)*(-1)).*theta).*k.*rou+exp(1).^(sqrt(-1).*theta) ...
  .*k.*rou+(sqrt(-1)*2).*exp(1).^((sqrt(-1)*(-2)).*theta).*rou.^2.*t+(sqrt(-1)*(-2)).*exp(1).^((sqrt( ...
  -1)*2).*theta).*rou.^2.*t+(sqrt(-1)*4).*theta+(-1).*exp(1).^((sqrt(-1)*(-1)).*theta).*rou.*((-1).*k+ ...
  (-1).*x0)+(-1).*exp(1).^(sqrt(-1).*theta).*rou.*((-1).*k+(-1).*x0)).*((-1).*exp(1).^((sqrt(-1)*(-1)) ...
  .*theta).*rou+(-1).*exp(1).^(sqrt(-1).*theta).*rou).^(-1).*(exp(1).^((sqrt(-1)*(-1)).*theta).*rou+ ...
  exp(1).^(sqrt(-1).*theta).*rou).^(-1));